<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>SalesManagement.Application</RootNamespace>
    <AssemblyName>SalesManagement.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SalesManagement.Domain\SalesManagement.Domain.csproj" />
  </ItemGroup>

</Project>
